# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmic', '0002_drainfields_onsitewaste_onsitewastewater_septic_tanks_trails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsitewaste',
            name='inspecti_1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='onsitewaste',
            name='inspection',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='onsitewaste',
            name='last_pumpe',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='onsitewaste',
            name='tnk_last_p',
            field=models.DateField(null=True),
        ),
    ]
