# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-24 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmic', '0003_auto_20190424_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsitewastewater',
            name='inspected',
            field=models.DateField(null=True),
        ),
    ]
