# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmic', '0004_auto_20190424_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsitewastewater',
            name='last_filte',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='onsitewastewater',
            name='last_inspe',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='onsitewastewater',
            name='lastpumped',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='onsitewastewater',
            name='pumped',
            field=models.DateField(null=True),
        ),
    ]
