                      List of relations
  Schema  |              Name              | Type  |  Owner   
----------+--------------------------------+-------+----------
 public   | auth_group                     | table | postgres
 public   | auth_group_permissions         | table | postgres
 public   | auth_permission                | table | postgres
 public   | auth_user                      | table | postgres
 public   | auth_user_groups               | table | postgres
 public   | auth_user_user_permissions     | table | postgres
 public   | comanche_boundaries            | table | postgres
 public   | comanche_caddo                 | table | postgres
 public   | comanche_cotton                | table | postgres
 public   | comanche_counties              | table | postgres
 public   | comanche_grady                 | table | postgres
 public   | comanche_jefferson             | table | postgres
 public   | comanche_kiowa                 | table | postgres
 public   | comanche_stephens              | table | postgres
 public   | comanche_tillman               | table | postgres
 public   | django_admin_log               | table | postgres
 public   | django_content_type            | table | postgres
 public   | django_migrations              | table | postgres
 public   | django_session                 | table | postgres
 public   | lbst_boundary                  | table | postgres
 public   | lbst_c_avoided_conversion      | table | postgres
 public   | lbst_counties                  | table | postgres
 public   | lbst_document                  | table | postgres
 public   | lbst_food_plots                | table | postgres
 public   | lbst_grasslands                | table | postgres
 public   | lbst_habitat_leases            | table | postgres
 public   | lbst_new_parcels               | table | postgres
 public   | lbst_parcels                   | table | postgres
 public   | lbst_shelterbelts              | table | postgres
 public   | lbst_trees_shrubs              | table | postgres
 public   | lbst_wetlands                  | table | postgres
 public   | raster_legend                  | table | postgres
 public   | raster_legendentry             | table | postgres
 public   | raster_legendentryorder        | table | postgres
 public   | raster_legendsemantics         | table | postgres
 public   | raster_rasterlayer             | table | postgres
 public   | raster_rasterlayerbandmetadata | table | postgres
 public   | raster_rasterlayermetadata     | table | postgres
 public   | raster_rasterlayerparsestatus  | table | postgres
 public   | raster_rasterlayerreprojected  | table | postgres
 public   | raster_rastertile              | table | postgres
 public   | spatial_ref_sys                | table | jbukoski
 public   | tamaya_ag                      | table | postgres
 public   | tamaya_boundary                | table | postgres
 public   | tamaya_buffered_bndry          | table | postgres
 public   | tamaya_document                | table | postgres
 public   | tamaya_forest_agc              | table | postgres
 public   | tamaya_forest_bgc              | table | postgres
 public   | tamaya_gssurgo_soc             | table | postgres
 public   | tamaya_landfire_classes        | table | postgres
 public   | tamaya_landfire_evt            | table | postgres
 public   | tamaya_mbls                    | table | postgres
 public   | tamaya_ndvi_2005               | table | postgres
 public   | tamaya_ndvi_2010               | table | postgres
 public   | tamaya_ndvi_2015               | table | postgres
 public   | tamaya_roads                   | table | postgres
 public   | tamaya_soil_data               | table | postgres
 public   | tamaya_subwatersheds           | table | postgres
 public   | tamaya_surfacehydro            | table | postgres
 public   | tamaya_vineyards               | table | postgres
 public   | tamaya_watersheds              | table | postgres
 topology | layer                          | table | jbukoski
 topology | topology                       | table | jbukoski
(63 rows)

