# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 20:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boundary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('acres', models.FloatField()),
                ('comments', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='bulk_density',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areasymbol', models.CharField(max_length=20)),
                ('spatialver', models.BigIntegerField()),
                ('musym', models.CharField(max_length=6)),
                ('mukey', models.CharField(max_length=30)),
                ('mukey_1', models.CharField(max_length=10)),
                ('db3rdbar', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='mbls',
            fields=[
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('mbl_field', models.IntegerField()),
                ('mbl_id', models.IntegerField()),
                ('acres', models.FloatField()),
                ('comment', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='roads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.FloatField()),
                ('rd_id', models.IntegerField(default=9999)),
                ('access', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=80)),
                ('surface', models.CharField(max_length=80)),
                ('condition', models.CharField(max_length=80)),
                ('rd_class', models.FloatField()),
                ('rd_type', models.CharField(max_length=80)),
                ('sa_id', models.CharField(max_length=80)),
                ('surf_type', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
                ('hunting', models.CharField(max_length=80)),
                ('comment', models.CharField(max_length=80)),
                ('restrict', models.CharField(max_length=80)),
                ('roadrepair', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
