# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='roads',
            name='id_field',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='roads',
            name='road_class',
            field=models.FloatField(max_length=254),
        ),
        migrations.AlterField(
            model_name='roads',
            name='road_type',
            field=models.CharField(max_length=254),
        ),
    ]
