# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 00:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='watersheds',
            fields=[
                ('watershed_id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.BigIntegerField()),
                ('source', models.BigIntegerField()),
                ('huc_8', models.CharField(max_length=8)),
                ('hu_8_name', models.CharField(max_length=80)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Watersheds',
            },
        ),
    ]
