# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 02:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulk_density',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areasymbol', models.CharField(max_length=20)),
                ('spatialver', models.BigIntegerField()),
                ('musym', models.CharField(max_length=6)),
                ('mukey', models.CharField(max_length=30)),
                ('mukey_1', models.CharField(max_length=10)),
                ('db3rdbar', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
