# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 19:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0002_auto_20170515_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='testRaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('name', models.TextField()),
            ],
        ),
    ]
