# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 21:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0002_soil_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil_ph',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
