# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0002_delete_testraster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_lines',
        ),
        migrations.DeleteModel(
            name='user_polygons',
        ),
        migrations.DeleteModel(
            name='user_pts',
        ),
    ]
