# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0003_testraster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testraster',
            name='id',
        ),
        migrations.AlterField(
            model_name='testraster',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
