# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 00:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0003_auto_20170219_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_pts',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
