# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 07:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0003_auto_20170712_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='landfire_evt',
            fields=[
                ('raster_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
    ]
