# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0004_auto_20170517_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testraster',
            old_name='name',
            new_name='rast_name',
        ),
    ]
