# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 22:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0005_composting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composting',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
