# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0006_auto_20170517_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testRaster',
        ),
    ]
