# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 22:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0006_auto_20170318_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxonomy',
            fields=[
                ('taxonomy_id', models.AutoField(primary_key=True, serialize=False)),
                ('areasymbol', models.CharField(max_length=20)),
                ('spatialver', models.BigIntegerField()),
                ('musym', models.CharField(max_length=6)),
                ('mukey', models.CharField(max_length=30)),
                ('mukey_1', models.CharField(max_length=10)),
                ('taxclname', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
