# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 22:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0007_delete_testraster'),
    ]

    operations = [
        migrations.CreateModel(
            name='testRaster',
            fields=[
                ('raster_id', models.TextField(default=1, primary_key=True, serialize=False)),
                ('name', models.TextField(default='tester')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
    ]
