# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 23:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0007_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='soil_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly_id', models.BigIntegerField()),
                ('areasymbol', models.CharField(max_length=20)),
                ('spatialver', models.BigIntegerField()),
                ('musym', models.CharField(max_length=6)),
                ('mukey', models.CharField(max_length=30)),
                ('mukey_1', models.CharField(max_length=10)),
                ('tax_class', models.CharField(max_length=254)),
                ('org_matter', models.FloatField()),
                ('composting', models.CharField(max_length=254)),
                ('texture', models.CharField(max_length=254)),
                ('ph_water', models.FloatField()),
                ('bulk_densi', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
