# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0010_user_lines_user_polygons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundary',
            options={'verbose_name_plural': 'Boundary'},
        ),
    ]
