# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 04:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0011_testraster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ndviDiff',
            fields=[
                ('raster_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
    ]
