# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0011_auto_20170320_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mbls',
            options={'verbose_name_plural': 'Master Business Leases'},
        ),
        migrations.AlterModelOptions(
            name='roads',
            options={'verbose_name_plural': 'Reservation Roads'},
        ),
        migrations.AlterModelOptions(
            name='soil_data',
            options={'verbose_name_plural': 'Soil Data'},
        ),
        migrations.AlterModelOptions(
            name='user_lines',
            options={'verbose_name_plural': 'User-defined Lines'},
        ),
        migrations.AlterModelOptions(
            name='user_polygons',
            options={'verbose_name_plural': 'User-defined Polygons'},
        ),
        migrations.AlterModelOptions(
            name='user_pts',
            options={'verbose_name_plural': 'User-defined Points'},
        ),
    ]
