# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0012_auto_20170806_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forest_agc',
            name='name',
        ),
        migrations.AlterField(
            model_name='forest_agc',
            name='raster_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
