# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 12:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0018_delete_forest_agc'),
    ]

    operations = [
        migrations.CreateModel(
            name='forest_agc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
    ]
