# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0027_landfire_evt_ndvi_2005_ndvi_2010_ndvi_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landfire_evt',
            old_name='raster',
            new_name='rast',
        ),
        migrations.RenameField(
            model_name='ndvi_2005',
            old_name='raster',
            new_name='rast',
        ),
        migrations.RenameField(
            model_name='ndvi_2010',
            old_name='raster',
            new_name='rast',
        ),
        migrations.RenameField(
            model_name='ndvi_2015',
            old_name='raster',
            new_name='rast',
        ),
    ]
