# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0030_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roads',
            name='distance',
        ),
    ]
