# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0031_remove_roads_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbls',
            name='mbls_id',
        ),
        migrations.AddField(
            model_name='mbls',
            name='acres_txt',
            field=models.CharField(default=-9999, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='boundary_1',
            field=models.BigIntegerField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='boundary_m',
            field=models.BigIntegerField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='dissolve',
            field=models.BigIntegerField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='entity',
            field=models.CharField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='entity2',
            field=models.CharField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='id',
            field=models.AutoField(auto_created=True, default=-9999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='lotid',
            field=models.CharField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='outbound_1',
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='outboundsp',
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='owner',
            field=models.CharField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbls',
            name='santa_ana',
            field=models.CharField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mbls',
            name='comment',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mbls',
            name='mbl_field',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='mbls',
            name='mbl_id',
            field=models.BigIntegerField(),
        ),
    ]
