# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0032_auto_20170821_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mbls',
        ),
    ]
