# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 19:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0033_delete_mbls'),
    ]

    operations = [
        migrations.CreateModel(
            name='mbls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('mbl_field', models.BigIntegerField()),
                ('mbl_id', models.BigIntegerField()),
                ('acres', models.FloatField()),
                ('entity', models.CharField(max_length=254)),
                ('outboundsp', models.FloatField()),
                ('outbound_1', models.FloatField()),
                ('comment', models.CharField(max_length=254)),
                ('boundary_m', models.BigIntegerField()),
                ('boundary_1', models.BigIntegerField()),
                ('lotid', models.CharField(max_length=254)),
                ('santa_ana', models.CharField(max_length=254)),
                ('owner', models.CharField(max_length=254)),
                ('acres_txt', models.CharField(max_length=254)),
                ('dissolve', models.BigIntegerField()),
                ('entity2', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Master Business Leases',
            },
        ),
    ]
