# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 19:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0034_mbls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('acres', models.FloatField()),
                ('use', models.CharField(max_length=254)),
                ('service', models.CharField(max_length=254)),
                ('ag_id', models.FloatField()),
                ('status', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('owner', models.CharField(max_length=254)),
                ('dissolve', models.BigIntegerField()),
                ('tract_numb', models.CharField(max_length=254)),
                ('ownership', models.CharField(max_length=254)),
                ('community', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
