# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-28 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0038_auto_20170821_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forest_agc',
        ),
        migrations.DeleteModel(
            name='forest_bgc',
        ),
        migrations.DeleteModel(
            name='gssurgo_soc',
        ),
        migrations.DeleteModel(
            name='landfire_classes',
        ),
        migrations.DeleteModel(
            name='landfire_evt',
        ),
        migrations.DeleteModel(
            name='ndvi_2005',
        ),
        migrations.DeleteModel(
            name='ndvi_2010',
        ),
        migrations.DeleteModel(
            name='ndvi_2015',
        ),
    ]
