# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 01:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='habitat_leases',
            fields=[
                ('lease_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lease_or_p', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('annual_cos', models.IntegerField()),
                ('total_acre', models.IntegerField()),
                ('payment_du', models.CharField(max_length=50)),
                ('contract_l', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Habitat Leases',
            },
        ),
    ]
