# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 04:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_plots',
            fields=[
                ('food_plot_id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('area', models.CharField(max_length=50)),
                ('plot_numbe', models.IntegerField()),
                ('acres', models.FloatField()),
                ('crop_2014', models.CharField(max_length=50)),
                ('crop_2015', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Food Plots',
            },
        ),
    ]
