# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-13 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0002_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lbst_boundary',
            new_name='boundary',
        ),
        migrations.RenameModel(
            old_name='lbst_new_parcels',
            new_name='new_parcels',
        ),
        migrations.RenameModel(
            old_name='lbst_parcels',
            new_name='parcels',
        ),
    ]
