# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 05:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0002_food_plots'),
    ]

    operations = [
        migrations.CreateModel(
            name='grasslands',
            fields=[
                ('grasslands_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('shape_area', models.FloatField()),
                ('year_done', models.IntegerField()),
                ('acres', models.FloatField()),
                ('cost', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Grassland Exports',
            },
        ),
        migrations.CreateModel(
            name='shelterbelts',
            fields=[
                ('shelterbelts_id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('operator', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
                ('cost', models.IntegerField()),
                ('size_ac', models.FloatField()),
                ('number_of_field', models.IntegerField()),
                ('year_done', models.IntegerField()),
                ('fabric_ft', models.IntegerField()),
                ('irrigated_field', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Homesite Shelterbelts',
            },
        ),
        migrations.CreateModel(
            name='trees_shrubs',
            fields=[
                ('trees_shrubs_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(max_length=24)),
                ('program', models.CharField(max_length=16)),
                ('practice', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=16)),
                ('cost_field', models.BigIntegerField()),
                ('size_ac_field', models.FloatField()),
                ('z_of_trees', models.BigIntegerField()),
                ('year_done', models.BigIntegerField()),
                ('fabric_ft', models.BigIntegerField()),
                ('irrigated', models.CharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Trees and Shrubs',
            },
        ),
        migrations.CreateModel(
            name='wetlands',
            fields=[
                ('wetlands_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=16)),
                ('practice', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=16)),
                ('cost_field', models.BigIntegerField()),
                ('size_ac_field', models.FloatField()),
                ('year_done', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Wetlands',
            },
        ),
    ]
