# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 04:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0003_auto_20171013_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_avoided_conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avoided_c_id', models.BigIntegerField()),
                ('mgmt_unit', models.CharField(max_length=25)),
                ('yr_establi', models.BigIntegerField()),
                ('acres', models.FloatField()),
                ('fid_1', models.BigIntegerField()),
                ('id_1', models.BigIntegerField()),
                ('mgmt_uni_1', models.CharField(max_length=254)),
                ('yr_estab_1', models.CharField(max_length=254)),
                ('sixteen_yr', models.BigIntegerField()),
                ('land_type', models.CharField(max_length=254)),
                ('threat', models.CharField(max_length=254)),
                ('acres_1', models.FloatField()),
                ('nrcs_pract', models.CharField(max_length=254)),
                ('peracreco2', models.FloatField()),
                ('peryrtonsc', models.FloatField()),
                ('tons_co2e_field', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statefp10', models.CharField(max_length=2)),
                ('countyfp10', models.CharField(max_length=3)),
                ('countyns10', models.CharField(max_length=8)),
                ('geoid10', models.CharField(max_length=5)),
                ('name10', models.CharField(max_length=100)),
                ('namelsad10', models.CharField(max_length=100)),
                ('lsad10', models.CharField(max_length=2)),
                ('classfp10', models.CharField(max_length=2)),
                ('mtfcc10', models.CharField(max_length=5)),
                ('csafp10', models.CharField(max_length=3)),
                ('cbsafp10', models.CharField(max_length=5)),
                ('metdivfp10', models.CharField(max_length=5)),
                ('funcstat10', models.CharField(max_length=1)),
                ('aland10', models.FloatField()),
                ('awater10', models.FloatField()),
                ('intptlat10', models.CharField(max_length=11)),
                ('intptlon10', models.CharField(max_length=12)),
                ('intptlat', models.FloatField()),
                ('intptlon', models.FloatField()),
                ('cnty_id', models.CharField(max_length=254)),
                ('id2', models.CharField(max_length=254)),
                ('geo', models.CharField(max_length=254)),
                ('target_geo', models.CharField(max_length=254)),
                ('target_g_1', models.CharField(max_length=254)),
                ('pop_total', models.BigIntegerField()),
                ('pop_hu', models.BigIntegerField()),
                ('pop_occ_hu', models.BigIntegerField()),
                ('pop_vac_hu', models.BigIntegerField()),
                ('shape_area', models.FloatField()),
                ('shape_len', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='avoided_c',
        ),
    ]
