# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 19:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0003_grasslands_shelterbelts_trees_shrubs_wetlands'),
    ]

    operations = [
        migrations.CreateModel(
            name='boundary',
            fields=[
                ('boundary_id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.BigIntegerField()),
                ('own_type', models.CharField(max_length=254)),
                ('own_name', models.CharField(max_length=254)),
                ('mgr_name_d', models.CharField(max_length=254)),
                ('p_des_tp', models.CharField(max_length=254)),
                ('p_loc_ds', models.CharField(max_length=254)),
                ('p_des_nm', models.CharField(max_length=254)),
                ('p_loc_nm', models.CharField(max_length=254)),
                ('s_des_tp', models.CharField(max_length=254)),
                ('s_loc_ds', models.CharField(max_length=254)),
                ('s_des_nm', models.CharField(max_length=254)),
                ('s_loc_nm', models.CharField(max_length=254)),
                ('t_des_tp', models.CharField(max_length=254)),
                ('t_loc_ds', models.CharField(max_length=254)),
                ('t_des_nm', models.CharField(max_length=254)),
                ('t_loc_nm', models.CharField(max_length=254)),
                ('state_nm', models.CharField(max_length=254)),
                ('gap_sts', models.CharField(max_length=254)),
                ('iucn_cat', models.CharField(max_length=254)),
                ('gis_src', models.CharField(max_length=254)),
                ('src_date', models.CharField(max_length=254)),
                ('comments', models.CharField(max_length=254)),
                ('gis_acres', models.FloatField()),
                ('status', models.CharField(max_length=254)),
                ('fia_code', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('res_status', models.CharField(max_length=254)),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Reservation Boundary',
            },
        ),
    ]
