# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0004_auto_20171020_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcels',
            options={},
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='parcel_id',
        ),
        migrations.AddField(
            model_name='parcels',
            name='id',
            field=models.AutoField(auto_created=True, default=9999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
