# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0004_boundary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='boundary',
            new_name='lbst_boundary',
        ),
    ]
