# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0006_auto_20171020_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='parcel_id',
            field=models.AutoField(default=9999, primary_key=True, serialize=False),
        ),
    ]
