# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0007_auto_20171020_0453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parcels',
        ),
    ]
