# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 18:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0007_lbst_new_parcels'),
    ]

    operations = [
        migrations.CreateModel(
            name='avoided_c',
            fields=[
                ('avoided_c_id', models.AutoField(primary_key=True, serialize=False)),
                ('feat_id', models.IntegerField()),
                ('mgmt_unit', models.CharField(max_length=25)),
                ('yr_establi', models.IntegerField()),
                ('acres', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
