# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0010_auto_20171020_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcels',
            old_name='parcel_id',
            new_name='id',
        ),
    ]
