# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0011_auto_20171020_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcels',
            old_name='id',
            new_name='parcel_id',
        ),
    ]
