# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 05:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0013_auto_20171020_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
