# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0019_auto_20171020_0626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grasslands',
            new_name='grasslands_export',
        ),
        migrations.AlterModelOptions(
            name='grasslands_export',
            options={},
        ),
        migrations.RenameField(
            model_name='grasslands_export',
            old_name='grasslands_id',
            new_name='id',
        ),
    ]
