# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0020_auto_20171020_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitat_leases',
            options={},
        ),
        migrations.RenameField(
            model_name='habitat_leases',
            old_name='lease_id',
            new_name='id',
        ),
    ]
