# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0021_auto_20171020_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelterbelts',
            options={},
        ),
        migrations.RenameField(
            model_name='shelterbelts',
            old_name='shelterbelts_id',
            new_name='id',
        ),
    ]
