# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0024_auto_20171021_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_avoided_conversion',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
