# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0028_auto_20171022_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_wetlands',
            old_name='wetland_id',
            new_name='wetlands_id',
        ),
    ]
