# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 21:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0030_forest_agc_forest_bgc_gssurgo_soc_landfire_classes_landfire_evt_ndvi_2005_ndvi_2010_ndvi_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='buffered_bndry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
