# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0031_buffered_bndry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gssurgo_soc',
        ),
    ]
