# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 15:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0032_delete_gssurgo_soc'),
    ]

    operations = [
        migrations.CreateModel(
            name='gssurgo_soc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
    ]
