# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 17:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbst', '0033_gssurgo_soc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wetlands',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
