# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-10-28 14:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcbc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='frog_bay_trails',
            fields=[
                ('state_fips', models.CharField(max_length=2)),
                ('county_fip', models.CharField(max_length=3)),
                ('road_name', models.CharField(max_length=100)),
                ('route_type', models.CharField(max_length=1)),
                ('tiger_feat', models.CharField(max_length=5)),
                ('shape_len', models.FloatField()),
                ('length', models.FloatField()),
                ('name', models.CharField(max_length=20)),
                ('layer', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='beachroute',
        ),
        migrations.DeleteModel(
            name='easyroute',
        ),
        migrations.DeleteModel(
            name='frogbaytrails',
        ),
        migrations.DeleteModel(
            name='rc_zoning_districts',
        ),
    ]
