# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-01-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcbc', '0003_auto_20191028_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundary',
            name='ani_firm',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='ani_tf',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='co_fips',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='com_nfo_id',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='comm_no',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='dfirm_id',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='pol_ar_id',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='pol_name1',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='pol_name2',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='pol_name3',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='source_cit',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='st_fips',
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='version_id',
        ),
        migrations.AddField(
            model_name='boundary',
            name='acres',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='perimeter',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='rbd4_field',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='rbd4_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='rbd4_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='shape_area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='shape_leng',
            field=models.FloatField(null=True),
        ),
    ]
