# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 06:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cotton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelid', models.CharField(max_length=34)),
                ('ag_acres', models.FloatField()),
                ('asd_acres', models.FloatField()),
                ('agparcelid', models.CharField(max_length=25)),
                ('parcelid_1', models.CharField(max_length=254)),
                ('owner', models.CharField(max_length=254)),
                ('addr1', models.CharField(max_length=254)),
                ('addr2', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('st', models.CharField(max_length=254)),
                ('zip', models.CharField(max_length=254)),
                ('school', models.BigIntegerField()),
                ('acres', models.FloatField()),
                ('ownerperc', models.FloatField()),
                ('mktland', models.BigIntegerField()),
                ('assdland', models.BigIntegerField()),
                ('mktimp', models.BigIntegerField()),
                ('assdimp', models.BigIntegerField()),
                ('mktother', models.BigIntegerField()),
                ('assdother', models.BigIntegerField()),
                ('exemption', models.BigIntegerField()),
                ('dblexempt', models.BigIntegerField()),
                ('image', models.CharField(max_length=254)),
                ('legal', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=-1)),
            ],
        ),
    ]
