# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 20:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comanche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=-1),
        ),
    ]
