# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 21:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('label', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=24)),
                ('acres', models.CharField(max_length=24)),
                ('parcel', models.CharField(max_length=24)),
                ('mpin', models.CharField(max_length=21)),
                ('problem', models.CharField(max_length=12)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
