# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 16:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boundaries',
            fields=[
                ('boundary_id', models.AutoField(primary_key=True, serialize=False)),
                ('aiannhce', models.CharField(max_length=4)),
                ('aiannhns', models.CharField(max_length=8)),
                ('affgeoid', models.CharField(max_length=13)),
                ('geoid', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('lsad', models.CharField(max_length=2)),
                ('aland', models.BigIntegerField()),
                ('awater', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
