# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 20:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comanche', '0002_auto_20170214_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caddo',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=-1),
        ),
        migrations.AlterField(
            model_name='cotton',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=-1),
        ),
    ]
