# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 21:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comanche', '0002_grady'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grady',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
