# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 21:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanche', '0003_auto_20170307_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='jefferson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('label', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=24)),
                ('acres', models.CharField(max_length=24)),
                ('parcel', models.CharField(max_length=24)),
                ('mpin', models.CharField(max_length=21)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='kiowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('parcelnum', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('acreage', models.FloatField()),
                ('parcelid', models.CharField(max_length=254)),
                ('owner', models.CharField(max_length=254)),
                ('addr1', models.CharField(max_length=254)),
                ('addr2', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('st', models.CharField(max_length=254)),
                ('zip', models.CharField(max_length=254)),
                ('school', models.CharField(max_length=254)),
                ('acres', models.FloatField()),
                ('ownerperc', models.FloatField()),
                ('mktland', models.IntegerField()),
                ('assdland', models.IntegerField()),
                ('mktimp', models.IntegerField()),
                ('assdimp', models.IntegerField()),
                ('mktother', models.IntegerField()),
                ('assdother', models.IntegerField()),
                ('exemption', models.IntegerField()),
                ('dblexempt', models.IntegerField()),
                ('image', models.CharField(max_length=254)),
                ('legal', models.CharField(max_length=254)),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='stephens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('label', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=24)),
                ('acres', models.CharField(max_length=24)),
                ('parcel', models.CharField(max_length=24)),
                ('mpin', models.CharField(max_length=21)),
                ('account', models.CharField(max_length=9)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='tillman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('label', models.CharField(max_length=5)),
                ('owner', models.CharField(max_length=24)),
                ('acres', models.CharField(max_length=24)),
                ('parcel', models.CharField(max_length=24)),
                ('mpin', models.CharField(max_length=21)),
                ('shape_leng', models.FloatField()),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
