# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 07:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boundary',
            fields=[
                ('boundary_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('acres', models.FloatField()),
                ('comments', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Boundary',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='tamaya/uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='mbls',
            fields=[
                ('mbls_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('mbl_field', models.IntegerField()),
                ('mbl_id', models.IntegerField()),
                ('acres', models.FloatField()),
                ('comment', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Master Business Leases',
            },
        ),
        migrations.CreateModel(
            name='ndviDiff',
            fields=[
                ('raster_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='roads',
            fields=[
                ('roads_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('length', models.FloatField()),
                ('id_field', models.BigIntegerField()),
                ('access', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('number', models.CharField(max_length=254)),
                ('surface', models.CharField(max_length=254)),
                ('condition', models.CharField(max_length=254)),
                ('road_class', models.FloatField(max_length=254)),
                ('road_type', models.CharField(max_length=254)),
                ('sa_id', models.CharField(max_length=254)),
                ('surf_type', models.CharField(max_length=254)),
                ('status', models.CharField(max_length=254)),
                ('hunting', models.CharField(max_length=254)),
                ('comment', models.CharField(max_length=254)),
                ('restrict', models.CharField(max_length=254)),
                ('roadrepair', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Reservation Roads',
            },
        ),
        migrations.CreateModel(
            name='soil_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly_id', models.BigIntegerField()),
                ('areasymbol', models.CharField(max_length=20)),
                ('spatialver', models.BigIntegerField()),
                ('musym', models.CharField(max_length=6)),
                ('mukey', models.CharField(max_length=30)),
                ('mukey_1', models.CharField(max_length=10)),
                ('tax_class', models.CharField(max_length=254)),
                ('org_matter', models.FloatField()),
                ('composting', models.CharField(max_length=254)),
                ('texture', models.CharField(max_length=254)),
                ('ph_water', models.FloatField()),
                ('bulk_densi', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Soil Data',
            },
        ),
        migrations.CreateModel(
            name='subwatersheds',
            fields=[
                ('subwatershed_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('watershed', models.CharField(max_length=50)),
                ('subwatshed', models.IntegerField()),
                ('wsno', models.CharField(max_length=50)),
                ('acres', models.FloatField()),
                ('aveslope', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Subwatersheds',
            },
        ),
        migrations.CreateModel(
            name='surfacehydro',
            fields=[
                ('surfacehydro_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Surface hydrology',
            },
        ),
        migrations.CreateModel(
            name='testRaster',
            fields=[
                ('raster_id', models.TextField(default=23, primary_key=True, serialize=False)),
                ('name', models.TextField(default='tester')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='user_lines',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'User-defined Lines',
            },
        ),
        migrations.CreateModel(
            name='user_polygons',
            fields=[
                ('polygon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'User-defined Polygons',
            },
        ),
        migrations.CreateModel(
            name='user_pts',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'User-defined Points',
            },
        ),
        migrations.CreateModel(
            name='watersheds',
            fields=[
                ('watershed_id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.BigIntegerField()),
                ('source', models.BigIntegerField()),
                ('huc_8', models.CharField(max_length=8)),
                ('hu_8_name', models.CharField(max_length=80)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Watersheds',
            },
        ),
    ]
