# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0004_landfire_evt'),
    ]

    operations = [
        migrations.CreateModel(
            name='landfire_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('label', models.TextField()),
            ],
        ),
    ]
