# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0006_auto_20170715_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfire_classes',
            name='value',
            field=models.FloatField(),
        ),
    ]
