# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0016_forest_agc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forest_agc',
            name='agc_id',
        ),
        migrations.RemoveField(
            model_name='forest_agc',
            name='name',
        ),
        migrations.AddField(
            model_name='forest_agc',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
