# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0017_auto_20170806_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forest_agc',
        ),
    ]
