# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0024_auto_20170807_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='landfire_evt',
        ),
    ]
