# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0025_delete_landfire_evt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ndvi_2005',
        ),
        migrations.DeleteModel(
            name='ndvi_2010',
        ),
        migrations.DeleteModel(
            name='ndvi_2015',
        ),
    ]
