# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 09:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0028_auto_20170807_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='buffered_bndry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
