# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 22:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0035_ag'),
    ]

    operations = [
        migrations.CreateModel(
            name='vineyards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vineyard_id', models.BigIntegerField()),
                ('acres', models.FloatField()),
                ('section', models.CharField(max_length=254)),
                ('soc_count', models.FloatField()),
                ('soc_sum', models.FloatField()),
                ('soc_mean', models.FloatField()),
                ('soc_min', models.FloatField()),
                ('soc_max', models.FloatField()),
                ('soctotal', models.FloatField()),
                ('socmean', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
