# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamaya', '0037_auto_20170821_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ag',
            name='soc_count',
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ag',
            name='soc_mean',
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ag',
            name='soc_sum',
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ag',
            name='socmean',
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ag',
            name='soctotal',
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
    ]
