# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-06-06 19:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buff_bndry',
            fields=[
                ('fid', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
