# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-08-24 03:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbt', '0003_counties_nsi_flowlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='existing_wm',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='lagoon',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='lift_stations',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pumphouses',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('storage', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='sewage_lines',
            fields=[
                ('fnode_field', models.IntegerField()),
                ('tnode_field', models.IntegerField()),
                ('lpoly_field', models.IntegerField()),
                ('rpoly_field', models.IntegerField()),
                ('length', models.FloatField()),
                ('sewer_field', models.IntegerField()),
                ('sewer_id', models.IntegerField()),
                ('desc_field', models.CharField(max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='storage_tanks',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
