# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-12-17 18:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbt', '0004_existing_wm_lagoon_lift_stations_pumphouses_sewage_lines_storage_tanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='res_soils',
            fields=[
                ('areasymbol', models.CharField(max_length=80)),
                ('spatialver', models.FloatField()),
                ('musym', models.CharField(max_length=80)),
                ('mukey', models.CharField(max_length=80)),
                ('mu_name', models.CharField(max_length=143)),
                ('mu_farmcls', models.CharField(max_length=133)),
                ('co_drain', models.CharField(max_length=80)),
                ('co_geomrp', models.CharField(max_length=80)),
                ('co_taxcl', models.CharField(max_length=89)),
                ('co_mstrcls', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
