# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-12-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbt', '0005_res_soils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_soils',
            old_name='co_drain',
            new_name='drainage',
        ),
        migrations.RenameField(
            model_name='res_soils',
            old_name='mu_farmcls',
            new_name='farm_class',
        ),
        migrations.RenameField(
            model_name='res_soils',
            old_name='co_geomrp',
            new_name='geomorph',
        ),
        migrations.RenameField(
            model_name='res_soils',
            old_name='co_taxcl',
            new_name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='res_soils',
            name='co_mstrcls',
        ),
        migrations.AddField(
            model_name='res_soils',
            name='grt_group',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='res_soils',
            name='moisture',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='res_soils',
            name='soil_order',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='res_soils',
            name='suborder',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
