# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-29 00:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buff_bndry',
            fields=[
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
