# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='ssmt/uploaded'),
        ),
    ]
