# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-15 04:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmt', '0002_auto_20190712_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ceded_territories',
            fields=[
                ('label', models.CharField(max_length=48)),
                ('treaty', models.BigIntegerField()),
                ('disputed', models.BigIntegerField()),
                ('website_la', models.CharField(max_length=14)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='boundary',
            name='affgeoid',
            field=models.CharField(max_length=13),
        ),
    ]
