# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-29 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssmt', '0002_buff_bndry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parcels',
            new_name='boundary',
        ),
    ]
