# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-15 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmt', '0003_auto_20190715_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='affgeoid',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
