# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-08 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jskt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jskt_counties',
            new_name='counties',
        ),
    ]
