# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jskt', '0002_auto_20190508_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_prop',
            name='cdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='all_prop',
            name='edit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='all_prop',
            name='mdoc_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='all_prop',
            name='rdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='all_prop',
            name='survey',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='all_prop',
            name='trust_da',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cl_co_prop_db',
            name='cdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cl_co_prop_db',
            name='edit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cl_co_prop_db',
            name='mdoc_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cl_co_prop_db',
            name='rdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cl_co_prop_db',
            name='survey',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cl_co_prop_db',
            name='trust_da',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_trust',
            name='cdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_trust',
            name='edit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_trust',
            name='mdoc_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_trust',
            name='rdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_trust',
            name='survey',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_trust',
            name='trust_da',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='res_trust',
            name='cdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='res_trust',
            name='edit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='res_trust',
            name='mdoc_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='res_trust',
            name='rdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='res_trust',
            name='survey',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='res_trust',
            name='trust_da',
            field=models.DateField(null=True),
        ),
    ]
